version: "2"
services:
  node:
    image: "node"
    restart: "always"
    logging:
      driver: "json-file"
      options:
        options:max-file: "10"
        max-size: "10m"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=4000
    volumes:
      - ./:/home/node/app
    ports:
      - "4000:4000"
    command: "npm run server"
